FROM python:alpine3.11 as dev

WORKDIR /app

COPY ./src/ /app/

RUN adduser \
    --disabled-password \
    --gecos "app user" \
    --home "/app" \
    --no-create-home \
    "app" \
    && apk update \
    && apk upgrade \
    && apk add bash curl \
    && mkdir -p /app/.kube \
    && chown -R app: /app/.kube
    
COPY ./src/requirements_dev.txt /app/requirements.txt

RUN curl -LO https://github.com/vmware-tanzu/velero/releases/download/v1.5.1/velero-v1.5.1-linux-amd64.tar.gz \
    && tar -xf velero-v1.5.1-linux-amd64.tar.gz \
    && cp velero-v1.5.1-linux-amd64/velero /usr/local/bin/velero \
    && rm -rf velero-v1.5.1-linux-amd64* \
    && chmod 755 /usr/local/bin/velero

RUN pip install --upgrade pip && pip install -r /app/requirements.txt 

USER app

ENTRYPOINT ["python", "server.py"]
